# HOME
p_cloud_platform_homepage:
    path:     /
    defaults: { _controller: PCloudPlatformBundle:Advert:index }

# ADD A USER TO THE DATABASE
add_user:
    path: /signup/
    defaults: { _controller: PCloudPlatformBundle:Advert:signup }

# DELETE A USER FROM THE DATABASE
delete_user:
   path: /deleteuser/
   defaults: { _controller: PCloudPlatformBundle:Advert:deleteuser }

# LOGIN A USER TO THE DATABASE
connect_user:
    path: /login/
    defaults: { _controller: PCloudPlatformBundle:Advert:login }

# EDIT A USER'S INFORMATION
edit_user:
    path: /edit/
    defaults: { _controlle: PCloudPlatformBundle:Advert:edituser }
