# Home
p_cloud_platform_homepage:
    path:     /
    defaults: { _controller: PCloudPlatformBundle:Advert:index }

# Add a user to the database
add_user:
    path: /signup/
    defaults: { _controller: PCloudPlatformBundle:Advert:signup }

# Delete a user from the database
delete_user:
   path: /deleteuser/
   defaults: { _controller: PCloudPlatformBundle:Advert:deleteuser }

# Login a user to the database
connect_user:
    path: /login/
    defaults: { _controller: PCloudPlatformBundle:Advert:login }

# Edit a user's informations
edit_user:
    path: /edit/
    defaults: { _controller: PCloudPlatformBundle:Advert:edituser }
view_users:
    path: /viewusers/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewusers }
