# -------------------
# ROUTING.YML (CLOUD)
# -------------------

# Accueil
p_cloud_platform_homepage:
    path:     /
    defaults: { _controller: PCloudPlatformBundle:Advert:index }

# Inscrire un utilisateur à la base de données
signup:
    path: /signup/
    defaults: { _controller: PCloudPlatformBundle:Advert:signup }

# Logger un utilisateur à la base de données
login:
    path: /login/
    defaults: { _controller: PCloudPlatformBundle:Advert:login }


# -----------------------
# ROUTES DE VISUALISATION
# -----------------------
# Voir la liste des utilisateurs
view_users:
    path: /viewusers/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewusers }

# Voir la liste des groupes d'utilisateurs
view_usersgroups:
    path: /viewusersgroups/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewusersgroups }

# Voir la liste des fichiers
view_files:
    path: /viewfiles/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewfiles }

# Voir la liste des groupes de fichiers
view_filesgroups:
    path: /viewfilesgroups/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewfilesgroups }

# Créer un utilisateur
creat_user:
    path: /creatuser/
    defaults: { _controller: PCloudPlatformBundle:Advert:creatuser }


# -------------------------
# ROUTES D'AJOUT DE DONNEES
# -------------------------
# Ajout d'un utilisateur dans la base de données
add_user:
    path: /adduser/
    defaults: { _controller: PCloudPlatformBundle:Advert:adduser }

# Ajout d'un fichier dans la base de données
add_file:
    path: /addfile/
    defaults: { _controller: PCloudPlatformBundle:Advert:addfile }

# Ajout d'un group d'utilisateurs dans la base de données
add_usergroup:
    path: /addusergroup/
    defaults: { _controller: PCloudPlatformBundle:Advert:addusergroup }

# Ajout d'un groupe de fichiers dans la base de données
add_filegroup:
    path: /addfilegroup/
    defaults: { _controller: PCloudPlatformBundle:Advert:addfilegroup }


# -------------------------------
# ROUTES DE SUPPRESION DE DONNEES
# -------------------------------
# Suppression d'un utilisateur de la base de données
delete_user:
   path: /deleteuser/{id}
   defaults: { _controller: PCloudPlatformBundle:Advert:deleteuser }
   requirements:
       id: \d+

# Suppression d'un fichier de la base de données
delete_file:
   path: /deletefile/{id}
   defaults: { _controller: PCloudPlatformBundle:Advert:deletefile }
   requirements:
       id: \d+

# Suppression d'un groupe d'utilisateurs de la base de données
delete_usergroup:
   path: /deleteusergroup/{id}
   defaults: { _controller: PCloudPlatformBundle:Advert:deleteusergroup }
   requirements:
       id: \d+

# Suppression d'un groupe de fichiers de la base de données
delete_filegroup:
   path: /deletefilegroup/{id}
   defaults: { _controller: PCloudPlatformBundle:Advert:deletefilegroup }
   requirements:
       id: \d+


# ---------------------------------
# ROUTES DE MODIFICATION DE DONNEES
# ---------------------------------
# Edition des informations d'un utilisateur
edit_user:
    path: /edituser/
    defaults: { _controller: PCloudPlatformBundle:Advert:edituser }

# Edition des informations d'un fichier
edit_file:
    path: /editfile/
    defaults: { _controller: PCloudPlatformBundle:Advert:editfile }

# Edition des informations d'un fichier
edit_usergroup:
    path: /editusergroup/
    defaults: { _controller: PCloudPlatformBundle:Advert:editusergroup }

# Edition des informations d'un fichier
edit_filegroup:
    path: /editfilegroup/
    defaults: { _controller: PCloudPlatformBundle:Advert:editfilegroup }
