p_cloud_platform_homepage:
    path:     /hello/{name}
    defaults: { _controller: PCloudPlatformBundle:Default:index }

hello_the_world:
    path: /hello-world
    defaults: { _controller: PCloudPlatformBundle:Advert:index }