# Accueil
p_cloud_platform_homepage:
    path:     /
    defaults: { _controller: PCloudPlatformBundle:Advert:index }

# Inscrire un utilisateur à la base de données
add_user:
    path: /signup/
    defaults: { _controller: PCloudPlatformBundle:Advert:signup }

# Supprimer un utilisateur de la base de données
delete_user:
   path: /deleteuser/
   defaults: { _controller: PCloudPlatformBundle:Advert:deleteuser }

# Logger un utilisateur à la base de données
connect_user:
    path: /login/
    defaults: { _controller: PCloudPlatformBundle:Advert:login }

# Editer les informations d'un utilisateur
edit_user:
    path: /edit/
    defaults: { _controller: PCloudPlatformBundle:Advert:edituser }

# Voir la liste des utilisateurs
view_users:
    path: /viewusers/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewusers }

# Voir la liste des groupes d'utilisateurs
view_usersgroups:
    path: /viewusersgroups/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewusersgroups }

# Voir la liste des fichiers
view_files:
    path: /viewfiles/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewfiles }

# Voir la liste des groupes de fichiers
view_filesgroups:
    path: /viewfilesgroups/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewfilesgroups }
