p_cloud_platform_homepage:
    path:     /
    defaults: { _controller: PCloudPlatformBundle:Advert:index }

hello_the_world:
    path: /hello-world
    defaults: { _controller: PCloudPlatformBundle:Advert:index }

p_cloud_platform_view:
    path: /advert/{id}
    defaults: { _controller: PCloudPlatformBundle:Advert:view }
    requirements:
        id: \d+