# -------------------
# ROUTING.YML - CLOUD
# -------------------

# Accueil
p_cloud_platform_homepage:
    path:     /
    defaults: { _controller: PCloudPlatformBundle:Advert:index }

# Inscrire un utilisateur à la base de données
signup:
    path: /signup/
    defaults: { _controller: PCloudPlatformBundle:Advert:signup }

# Logger un utilisateur à la base de données
login:
    path: /login/
    defaults: { _controller: PCloudPlatformBundle:Advert:login }


# -----------------------
# ROUTES DE VISUALISATION
# -----------------------
# Voir la liste des utilisateurs
view_users:
    path: /viewusers/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewusers }

# Voir la liste des groupes d'utilisateurs
view_usersgroups:
    path: /viewusersgroups/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewusersgroups }

# Voir la liste des fichiers
view_files:
    path: /viewfiles/{grant}/{view}
    defaults: { _controller: PCloudPlatformBundle:Advert:viewfiles }

# Voir la liste des groupes de fichiers
view_filesgroups:
    path: /viewfilesgroups/
    defaults: { _controller: PCloudPlatformBundle:Advert:viewfilesgroups }

# Voir UN utilisateur
view_singleuser:
    path: /viewsingleuser/{id}
    defaults: { _controller: PCloudPlatformBundle:Advert:viewsingleuser }

# Voir UN fichier
view_singlefile:
    path: /viewsinglefile/{id}
    defaults: { _controller: PCloudPlatformBundle:Advert:viewsinglefile }
    requirements:
        id: \d+

# Voir UN groupe d'utilisateurs
view_singleusergroup:
    path: /viewsingleusergroup/{id}
    defaults: { _controller: PCloudPlatformBundle:Advert:viewsingleusergroup }
    requirements:
        id: \d+

# Voir UN groupe de fichiers
view_singlefilegroup:
    path: /viewsinglefilegroup/{id}
    defaults: { _controller: PCloudPlatformBundle:Advert:viewsinglefilegroup }
    requirements:
        id: \d+

# Voir les accès d'un group d'utilisateurs
view_usergroupAccess:
    path: /viewusergroupAccess/{id}
    defaults: { _controller: PCloudPlatformBundle:Advert:viewusergroupAccess }
    requirements:
        id: \d+


# -------------------------
# ROUTES D'AJOUT DE DONNEES
# -------------------------
# Ajout d'un utilisateur dans la base de données
add_user:
    path: /adduser/
    defaults: { _controller: PCloudPlatformBundle:Advert:adduser }

# Ajout d'un fichier dans la base de données
add_file:
    path: /addfile/{grant}
    defaults: { _controller: PCloudPlatformBundle:Advert:addfile }

# Ajout d'un group d'utilisateurs dans la base de données
add_usergroup:
    path: /addusergroup/
    defaults: { _controller: PCloudPlatformBundle:Advert:addusergroup }

# Ajout d'un groupe de fichiers dans la base de données
add_filegroup:
    path: /addfilegroup/
    defaults: { _controller: PCloudPlatformBundle:Advert:addfilegroup }



# -------------------------------
# ROUTES DE SUPPRESION DE DONNEES
# -------------------------------
# Suppression d'un utilisateur de la base de données
delete_user:
   path: /deleteuser/{id}
   defaults: { _controller: PCloudPlatformBundle:Advert:deleteuser }
   requirements:
       id: \d+

# Suppression d'un fichier de la base de données
delete_file:
   path: /deletefile/{grant}/{view}/{id}
   defaults: { _controller: PCloudPlatformBundle:Advert:deletefile }
   requirements:
       id: \d+

# Suppression d'un groupe d'utilisateurs de la base de données
delete_usergroup:
   path: /deleteusergroup/{id}
   defaults: { _controller: PCloudPlatformBundle:Advert:deleteusergroup }
   requirements:
       id: \d+

# Suppression d'un groupe de fichiers de la base de données
delete_filegroup:
   path: /deletefilegroup/{id}/{title}
   defaults: { _controller: PCloudPlatformBundle:Advert:deletefilegroup }
   requirements:
       id: \d+


# ---------------------------------
# ROUTES DE MODIFICATION DE DONNEES
# ---------------------------------
# Edition des informations d'un utilisateur
edit_user:
    path: /edituser/
    defaults: { _controller: PCloudPlatformBundle:Advert:edituser }

# Edition des informations d'un fichier
edit_file:
    path: /editfile/{grant}
    defaults: { _controller: PCloudPlatformBundle:Advert:editfile }

# Edition des informations d'un fichier
edit_usergroup:
    path: /editusergroup/
    defaults: { _controller: PCloudPlatformBundle:Advert:editusergroup }

# Edition des informations d'un fichier
edit_filegroup:
    path: /editfilegroup/
    defaults: { _controller: PCloudPlatformBundle:Advert:editfilegroup }


# ------------------------------------
# ROUTES CONCERNANT LES DROITS D'ACCES
# ------------------------------------
# Ajout d'une vue
addview_filegroup:
    path: /addview/{id}/{title}
    defaults: { _controller: PCloudPlatformBundle:Advert:addview }

# Suppression d'une vue
deleteview_filegroup:
    path: /deleteview/{title}
    defaults: { _controller: PCloudPlatformBundle:Advert:deleteview }

# Ajout d'un utilisateur pour se connecter à mysql
addgrant_filegroup:
    path: /addgrant/{user}
    defaults: { _controller: PCloudPlatformBundle:Advert:addgrant }

# Ajout d'un droit d'accès sur une vue pour un utilisateur
addgrantonview:
    path: /addgrantonview/{user}/{view}
    defaults: { _controller: PCloudPlatformBundle:Advert:addgrantonview }

# Ajout d'un droit d'accès sur une vue pour un utilisateur
deletegrantfromview:
    path: /deletegrantfromview/{user}/{view}
    defaults: { _controller: PCloudPlatformBundle:Advert:deletegrantfromview }


# Ajout d'une entrée dans la table access
# indiquant les groupes de fichiers dont un groupe d'utilisateurs a le droit de voir
add_access:
    path: /addaccess/{usersgroupsid}/{filesgroupsid}/{write}
    defaults: { _controller: PCloudPlatformBundle:Advert:addaccess }
    requirements:
        usersgroupsid: \d+
        filesgroupsid: \d+
        write        : \d+

deleteaccess:
    path: /deleteaccess/{usersgroupsid}/{filesgroupsid}
    defaults: { _controller: PCloudPlatformBundle:Advert:deleteaccess }

# Récupère les droits d'un groupe d'utilisateurs
getusergrant:
    path: /getusergrant/{groupid}
    defaults: { _controller: PCloudPlatformBundle:Advert:getusergrant }

# Récupère les groupes de fichiers dont un groupe d'utilisateurs a le droit de voir
getaccess:
    path: /getaccess/{usersgroupsid}
    defaults: { _controller: PCloudPlatformBundle:Advert:getaccess }

# ---------
# RECHERCHE
# ---------
search:
    path: /search/{terms}
    defaults: { _controller: PCloudPlatformBundle:Advert:search }
